### ISSUE TITLE
Agregar parámetro a etiqueta meta

### ISSUE THREAD

**Issue by Gab-Serrano** [Gab-Serrano/web-tienda-enchanteur#11]
La etiqueta `meta` **en todas las páginas** debe ser como la siguiente: `<meta name="viewport" content="width=device-width, initial-scale=1.0 minimum-scale=1" />` para que funcione en el `.navbar` el sticky -top.

**Comment by DinoDG** [comment]
voy a cambiar las mias (Login y Contacto) y vuelvo a pushear
